Feature/#3
Zhilg/BMSTU_TeamDev pull request #10
Opened 2024-04-18 16:22 UTC by ak-karimzai

**Сделание задачи**

- В папке `model` реализации модель пользователя.
-  В папке `managers` реализации бизнес-логику.

2024-04-19 19:45 UTC, Andebugan requested changes
В общем по коду всё нормально, но надо дописать докстринги и убрать лишнее

2024-04-19 19:45 UTC, Andebugan commented on lms/models/models.py
Комментарии убрать (не нужны)

2024-04-19 19:45 UTC, Andebugan commented on lms/managers/managers.py
Комментарии убрать, заменить на докстринги для класса и реализованных методов

2024-04-19 20:31 UTC, ak-karimzai commented on lms/models/models.py
убрал

2024-04-19 20:31 UTC, ak-karimzai commented on lms/managers/managers.py
добавил

2024-04-20 18:51 UTC, Zhilg commented
данная задача была разбита на подзадачи и решена по отдельности, закрываю issue

2024-04-20 18:54 UTC, closed without merging